AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  SageMakerProcessingJobRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSageMakerFullAccess'
  WaitingStateMachineRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: 'The training jobs name are arbitrary when sending jobs to the queue. The user could a suitable prefix.'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: LambdaWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: !GetAtt LeaveFunction.Arn
        - PolicyName: SageMakerReadWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'sagemaker:CreateProcessingJob'
                  - 'sagemaker:DescribeProcessingJob'
                Resource: '*'
        - PolicyName: PassRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: !GetAtt SageMakerProcessingJobRole.Arn
  WaitingStateMachine:
    Type: 'AWS::Serverless::StateMachine'
    Properties:
      DefinitionUri: statemachine/waiting.asl.json
      DefinitionSubstitutions:
        LeaveFunctionArn: !GetAtt LeaveFunction.Arn
      Role: !GetAtt WaitingStateMachineRole.Arn
  Queue:
    Type: 'AWS::SQS::Queue'
    Properties:
      FifoQueue: True
      MessageRetentionPeriod: 345600
      QueueName: 'SageMakerJobs.fifo'
      VisibilityTimeout: 30
      KmsMasterKeyId: 'alias/aws/sqs'
  EnterLambdaRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: 'The log groups are created by Lambda'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CloudWatchWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: DynamoWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'dynamodb:UpdateItem'
                Resource: !GetAtt CounterTable.Arn
        - PolicyName: StepFunctionsWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'states:StartExecution'
                Resource: !Ref WaitingStateMachine
        - PolicyName: QueueRead
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource: !GetAtt Queue.Arn
  EnterFunction:
    Type: 'AWS::Serverless::Function'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: 'We do not assume the user has a VPC. The user should add their own VPC if desired.'
    Properties:
      CodeUri: functions/enter/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref CounterTable
          STATE_MACHINE_ARN: !Ref WaitingStateMachine
      Role: !GetAtt EnterLambdaRole.Arn
      ReservedConcurrentExecutions: 10
  LeaveLambdaRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: 'The log groups are created by Lambda'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CloudWatchWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: DynamoWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'dynamodb:UpdateItem'
                Resource: !GetAtt CounterTable.Arn
  LeaveFunction:
    Type: 'AWS::Serverless::Function'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: 'We do not assume the user has a VPC. The user should add their own VPC if desired.'
    Properties:
      CodeUri: functions/leave/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref CounterTable
      Role: !GetAtt LeaveLambdaRole.Arn
      ReservedConcurrentExecutions: 10
  SQSLambdaEventSource:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 1
      Enabled: True
      EventSourceArn: !GetAtt Queue.Arn
      FunctionName: !Ref EnterFunction
      FunctionResponseTypes:
        - 'ReportBatchItemFailures'
  CounterTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: "InstanceType"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "InstanceType"
            KeyType: "HASH"
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: True
        BillingMode: 'PAY_PER_REQUEST'
        SSESpecification:
          SSEEnabled: True
Outputs:
  CounterTableName:
    Value: !Ref CounterTable
    Export:
      Name: !Sub 'CounterTableName-${AWS::StackName}'
  SageMakerProcessingJobRoleArn:
    Value: !GetAtt SageMakerProcessingJobRole.Arn
    Export:
      Name: !Sub 'SageMakerProcessingJobArn-${AWS::StackName}'