AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  WaitingStateMachineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: LambdaWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'lambda:InvokeFunction'
                Resource: !GetAtt LeaveFunction.Arn
        - PolicyName: SageMakerReadWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'sagemaker:CreateProcessingJob'
                  - 'sagemaker:DescribeProcessingJob'
                Resource: '*'
        - PolicyName: PassRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'iam:PassRole'
                Resource: !Join
                  - ':'
                  - - 'arn'
                    - !Ref AWS::Partition
                    - 'iam'
                    - ''
                    - !Ref AWS::AccountId
                    - 'role/SageMaker*'
  WaitingStateMachine:
    Type: 'AWS::Serverless::StateMachine'
    Properties:
      DefinitionUri: statemachine/waiting.asl.json
      DefinitionSubstitutions:
        LeaveFunctionArn: !GetAtt LeaveFunction.Arn
      Role: !GetAtt WaitingStateMachineRole.Arn
  Queue:
    Type: 'AWS::SQS::Queue'
    Properties:
      FifoQueue: True
      MessageRetentionPeriod: 345600
      QueueName: 'SageMakerJobs.fifo'
      VisibilityTimeout: 30
  EnterLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CloudWatchWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: DynamoWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'dynamodb:UpdateItem'
                Resource: !GetAtt CounterTable.Arn
        - PolicyName: StepFunctionsWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'states:StartExecution'
                Resource: !Ref WaitingStateMachine
        - PolicyName: QueueRead
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource: !GetAtt Queue.Arn
  EnterFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: functions/enter/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref CounterTable
          STATE_MACHINE_ARN: !Ref WaitingStateMachine
      Role: !GetAtt EnterLambdaRole.Arn
  LeaveLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CloudWatchWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: DynamoWrite
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'dynamodb:UpdateItem'
                Resource: !GetAtt CounterTable.Arn
  LeaveFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: functions/leave/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref CounterTable
      Role: !GetAtt LeaveLambdaRole.Arn
  SQSLambdaEventSource:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      BatchSize: 1
      Enabled: True
      EventSourceArn: !GetAtt Queue.Arn
      FunctionName: !Ref EnterFunction
      FunctionResponseTypes:
        - 'ReportBatchItemFailures'
  CounterTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: "InstanceType"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "InstanceType"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1